-- MySQL Script generated by MySQL Workbench
-- Thu Jun 12 23:17:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db-fct
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-fct
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-fct` DEFAULT CHARACTER SET utf8mb3 ;
USE `db-fct` ;

-- -----------------------------------------------------
-- Table `db-fct`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`users` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`users` (
  `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` ENUM('ADMIN', 'TUTOR', 'COORDINADOR', 'ALUMNO') NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `updated_password_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`alumnos` (
  `alumno_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `convocatoria` INT NOT NULL DEFAULT '3',
  `dni` VARCHAR(9) NULL DEFAULT NULL,
  `nia` VARCHAR(8) NULL DEFAULT NULL,
  `nuss` VARCHAR(11) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`alumno_id`),
  INDEX `fk_alumnos_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`alumnos_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`alumnos_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`alumnos_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`archivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`archivos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`archivos` (
  `archivo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alumno_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `file` VARCHAR(255) NOT NULL,
  `type` ENUM('CV', 'ANEXO', 'JUSTIFICANTE', 'OTRO') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`archivo_id`),
  INDEX `fk_anexos_alumnos_idx` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `fk_anexos_alumnos`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db-fct`.`alumnos` (`alumno_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`ciclos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`ciclos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`ciclos` (
  `ciclo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Ciclo formativo',
  `name` VARCHAR(255) NOT NULL,
  `acronimo` VARCHAR(10) NOT NULL,
  `nivel` VARCHAR(15) NOT NULL,
  `familia_profesional` VARCHAR(255) NOT NULL,
  `horas_practicas` SMALLINT UNSIGNED NOT NULL COMMENT 'Determina las horas máximas de prácticas de cada ciclo',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ciclo_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`ciclos_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`ciclos_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`ciclos_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`coordinaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`coordinaciones` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`coordinaciones` (
  `coordinacion_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`coordinacion_id`),
  INDEX `fk_coordinaciones_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_coordinaciones_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`coordinaciones_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`coordinaciones_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`coordinaciones_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`ciclos_lectivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`ciclos_lectivos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`ciclos_lectivos` (
  `ciclo_lectivo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ciclo_lectivo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-fct`.`tutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutores` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutores` (
  `tutor_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`tutor_id`),
  INDEX `fk_tutores_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tutores_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`grupos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`grupos` (
  `grupo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ciclo_id` BIGINT UNSIGNED NOT NULL,
  `ciclo_lectivo_id` BIGINT UNSIGNED NOT NULL,
  `tutor_id` BIGINT UNSIGNED NOT NULL,
  `numero` TINYINT UNSIGNED NOT NULL,
  `horario` VARCHAR(15) NOT NULL,
  `anexo_ocho` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`grupo_id`),
  INDEX `fk_grupos_ciclos_idx` (`ciclo_id` ASC) VISIBLE,
  INDEX `fk_grupos_ciclos_lectivos1_idx` (`ciclo_lectivo_id` ASC) VISIBLE,
  INDEX `fk_grupos_tutores1_idx` (`tutor_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_ciclos`
    FOREIGN KEY (`ciclo_id`)
    REFERENCES `db-fct`.`ciclos` (`ciclo_id`),
  CONSTRAINT `fk_grupos_ciclos_lectivos1`
    FOREIGN KEY (`ciclo_lectivo_id`)
    REFERENCES `db-fct`.`ciclos_lectivos` (`ciclo_lectivo_id`),
  CONSTRAINT `fk_grupos_tutores1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `db-fct`.`tutores` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`cursos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`cursos` (
  `curso_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alumno_id` BIGINT UNSIGNED NOT NULL,
  `grupo_id` BIGINT UNSIGNED NOT NULL,
  `horas_hechas` TINYINT UNSIGNED NOT NULL,
  `rating` VARCHAR(15) NOT NULL DEFAULT 'Verde',
  `posibles_empresas` VARCHAR(1023) NOT NULL DEFAULT '',
  `observaciones` VARCHAR(2047) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`curso_id`),
  INDEX `fk_cursos_alumnos_idx` (`alumno_id` ASC) VISIBLE,
  INDEX `fk_cursos_grupos_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_alumnos`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db-fct`.`alumnos` (`alumno_id`),
  CONSTRAINT `fk_cursos_grupos`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `db-fct`.`grupos` (`grupo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`cursos_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`cursos_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`cursos_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`empresas` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`empresas` (
  `empresa_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `propuesta_por` BIGINT UNSIGNED NULL,
  `observaciones` VARCHAR(2047) NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `cif` VARCHAR(9) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `sector` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `numero_plazas` INT NULL,
  `persona_contacto` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_contacto` DATE NULL DEFAULT NULL,
  `hay_convenio` TINYINT NULL DEFAULT '0',
  `numero_convenio` VARCHAR(9) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`empresa_id`),
  INDEX `fk_empresas_users_idx` (`propuesta_por` ASC) VISIBLE,
  CONSTRAINT `fk_empresas_users`
    FOREIGN KEY (`propuesta_por`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`empresas_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`empresas_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`empresas_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutores_empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutores_empresas` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutores_empresas` (
  `tutor_empresa_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`tutor_empresa_id`),
  INDEX `fk_turores_empresas_empresas_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_turores_empresas_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`fcts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`fcts` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`fcts` (
  `fct_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `curso_id` BIGINT UNSIGNED NOT NULL,
  `empresa_id` BIGINT UNSIGNED NULL,
  `tutor_empresa_id` BIGINT UNSIGNED NULL,
  `motivo_renuncia` VARCHAR(45) NULL,
  `anexo_21` VARCHAR(5) NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `horas_semana` SMALLINT NULL,
  `no_lectivos` SMALLINT NULL,
  `horas_practicas` SMALLINT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `observaciones` VARCHAR(2047) NULL DEFAULT NULL,
  `apto` TINYINT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`fct_id`),
  INDEX `fk_fcts_empresas_idx` (`empresa_id` ASC) VISIBLE,
  INDEX `fk_fcts_turores_empresas_idx` (`tutor_empresa_id` ASC) VISIBLE,
  INDEX `fk_fcts_cursos1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_fcts_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`),
  CONSTRAINT `fk_fcts_tutores_empresas`
    FOREIGN KEY (`tutor_empresa_id`)
    REFERENCES `db-fct`.`tutores_empresas` (`tutor_empresa_id`),
  CONSTRAINT `fk_fcts_cursos1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db-fct`.`cursos` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`plazas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`plazas` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`plazas` (
  `plaza_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `ciclo_id` BIGINT UNSIGNED NOT NULL,
  `plazas` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`plaza_id`),
  INDEX `fk_plazas_empresas_idx` (`empresa_id` ASC) VISIBLE,
  INDEX `fk_plazas_ciclos_idx` (`ciclo_id` ASC) VISIBLE,
  CONSTRAINT `fk_plazas_ciclos`
    FOREIGN KEY (`ciclo_id`)
    REFERENCES `db-fct`.`ciclos` (`ciclo_id`),
  CONSTRAINT `fk_plazas_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`plazas_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`plazas_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`plazas_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`reviews` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`reviews` (
  `review_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `score` TINYINT NOT NULL COMMENT 'El valor debe estar comprometido entre 0 y 5.',
  `comment` VARCHAR(2047) NULL DEFAULT NULL,
  `estado` ENUM('VISIBLE', 'ELIMINADO') NULL DEFAULT 'VISIBLE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_resenias_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reviews_empresas_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`),
  CONSTRAINT `fk_reviews_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`reviews_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`reviews_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`reviews_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutores_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutores_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutores_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutorias` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutorias` (
  `tutoria_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grupo_id` BIGINT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`tutoria_id`),
  INDEX `fk_tutorias_grupos_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tutorias_grupos`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `db-fct`.`grupos` (`grupo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutorias_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutorias_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutorias_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`users_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`users_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`users_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `db-fct` ;

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_alumnos` (`tutor_id` INT, `user_id` INT, `nombre_alumno` INT, `email` INT, `alumno_id` INT, `convocatoria` INT, `dni` INT, `nia` INT, `nuss` INT, `phone` INT, `address` INT, `curso_id` INT, `horas_hechas` INT, `rating` INT, `observaciones` INT, `posibles_empresas` INT, `grupo_id` INT, `numero` INT, `ciclo_lectivo_id` INT, `nombre_ciclo_lectivo` INT, `acronimo` INT, `grupo_nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_grupos_ciclos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_grupos_ciclos` (`ciclo_lectivo_id` INT, `grupo_id` INT, `numero` INT, `ciclo_id` INT, `horas_practicas` INT, `grupo_nombre` INT, `tutor_id` INT, `name` INT, `email` INT, `user_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_tutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_tutores` (`user_id` INT, `name` INT, `email` INT, `tutor_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_coordinadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_coordinadores` (`user_id` INT, `name` INT, `email` INT, `coordinacion_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_cursos` (`curso_id` INT, `alumno_id` INT, `grupo_id` INT, `tutor_id` INT, `horas_hechas` INT, `rating` INT, `observaciones` INT, `posibles_empresas` INT, `numero` INT, `horario` INT, `anexo_ocho` INT, `ciclo_lectivo_id` INT, `ciclo_id` INT, `name` INT, `acronimo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_tutores_ciclo_lectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_tutores_ciclo_lectivo` (`tutor_id` INT, `user_id` INT, `name` INT, `email` INT, `grupo_id` INT, `numero` INT, `ciclo_id` INT, `ciclo_lectivo_id` INT, `nombre` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_all_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_all_alumnos` (`user_id` INT, `nombre_alumno` INT, `email` INT, `alumno_id` INT, `convocatoria` INT, `dni` INT, `nia` INT, `nuss` INT, `phone` INT, `address` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_alumnos_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_alumnos_curso` (`user_id` INT, `nombre_alumno` INT, `email` INT, `alumno_id` INT, `convocatoria` INT, `dni` INT, `nia` INT, `nuss` INT, `phone` INT, `address` INT, `curso_id` INT, `horas_hechas` INT, `rating` INT, `observaciones` INT, `posibles_empresas` INT, `grupo_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_empresas_plazas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_empresas_plazas` (`empresa_id` INT, `propuesta_por` INT, `observaciones` INT, `estado` INT, `nombre_empresa` INT, `cif` INT, `email` INT, `sector` INT, `address` INT, `phone` INT, `persona_contacto` INT, `fecha_contacto` INT, `hay_convenio` INT, `numero_convenio` INT, `plaza_id` INT, `plazas` INT, `ciclo_id` INT, `nombre_ciclo` INT, `acronimo` INT, `nivel` INT, `familia_profesional` INT, `horas_practicas` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_empresas_tutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_empresas_tutores` (`empresa_id` INT, `nombre` INT, `estado` INT, `cif` INT, `email` INT, `sector` INT, `address` INT, `phone` INT, `numero_plazas` INT, `persona_contacto` INT, `propuesta_por` INT, `hay_convenio` INT, `numero_convenio` INT, `fecha_contacto` INT, `observaciones` INT, `id_usuario` INT, `nombre_usuario` INT, `email_usuario` INT, `rol_usuario` INT, `tutor_empresa_id` INT, `nombre_tutor` INT, `email_tutor` INT, `telefono_tutor` INT, `dni_tutor` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`vista_alumno_ciclos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`vista_alumno_ciclos` (`ciclo_lectivo_id` INT, `grupo_id` INT, `numero` INT, `ciclo_id` INT, `grupo_nombre` INT, `alumno_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `db-fct`.`view_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-fct`.`view_reviews` (`review_id` INT, `user_id` INT, `empresa_id` INT, `score` INT, `comment` INT, `review_estado` INT, `propuesta_por` INT, `observaciones` INT, `empresa_estado` INT, `nombre_empresa` INT, `nombre_usuario` INT, `email` INT);

-- -----------------------------------------------------
-- View `db-fct`.`vista_alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_alumnos`;
DROP VIEW IF EXISTS `db-fct`.`vista_alumnos` ;
USE `db-fct`;
CREATE OR REPLACE VIEW `vista_alumnos` AS
    SELECT 
        t.tutor_id,
        u.user_id,
        u.name AS nombre_alumno,
        u.email,
        a.alumno_id,
        a.convocatoria,
        a.dni,
        a.nia,
        a.nuss,
        a.phone,
        a.address,
        c.curso_id,
        c.horas_hechas,
        c.rating,
        c.observaciones,
        c.posibles_empresas,
        g.grupo_id,
        g.numero,
        cl.ciclo_lectivo_id,
        cl.nombre AS nombre_ciclo_lectivo,
        ci.acronimo,
        CONCAT(g.numero, 'º (', ci.acronimo, ')') AS grupo_nombre
    FROM
        users u
            INNER JOIN
        alumnos a ON u.user_id = a.user_id
            INNER JOIN
        cursos c ON c.alumno_id = a.alumno_id
            INNER JOIN
        grupos g ON g.grupo_id = c.grupo_id
            AND g.deleted_at IS NULL
            INNER JOIN
        tutores t ON t.tutor_id = g.tutor_id
            INNER JOIN
        ciclos ci ON ci.ciclo_id = g.ciclo_id
            AND ci.deleted_at IS NULL
            INNER JOIN
        ciclos_lectivos cl ON g.ciclo_lectivo_id = cl.ciclo_lectivo_id
            AND cl.deleted_at IS NULL
    ORDER BY cl.nombre , g.numero , u.name;

-- -----------------------------------------------------
-- View `db-fct`.`vista_grupos_ciclos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_grupos_ciclos`;
DROP VIEW IF EXISTS `db-fct`.`vista_grupos_ciclos` ;
USE `db-fct`;
CREATE OR REPLACE VIEW `vista_grupos_ciclos` AS
    SELECT 
        cl.ciclo_lectivo_id,
        g.grupo_id,
        g.numero,
        ci.ciclo_id,
        ci.horas_practicas,
        CONCAT(g.numero, 'º (', ci.acronimo, ')') AS grupo_nombre,
        g.tutor_id,
		u.name,
        u.email,
        u.user_id
    FROM
        ciclos_lectivos cl
            INNER JOIN
        grupos g ON g.ciclo_lectivo_id = cl.ciclo_lectivo_id
            AND g.deleted_at IS NULL
            INNER JOIN
        ciclos ci ON ci.ciclo_id = g.ciclo_id
            AND ci.deleted_at IS NULL
		INNER JOIN tutores t ON t.tutor_id = g.tutor_id
        INNER JOIN users u ON u.user_id = t.user_id
    WHERE
        cl.deleted_at IS NULL;

-- -----------------------------------------------------
-- View `db-fct`.`vista_tutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_tutores`;
DROP VIEW IF EXISTS `db-fct`.`vista_tutores` ;
USE `db-fct`;
CREATE  OR REPLACE VIEW `vista_tutores` AS
    SELECT 
        u.user_id, u.name, u.email, t.tutor_id
    FROM
        tutores t
            INNER JOIN
        users u ON t.user_id = u.user_id;

-- -----------------------------------------------------
-- View `db-fct`.`vista_coordinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_coordinadores`;
DROP VIEW IF EXISTS `db-fct`.`vista_coordinadores` ;
USE `db-fct`;
CREATE  OR REPLACE VIEW `vista_coordinadores` AS
    SELECT 
        u.user_id, u.name, u.email, c.coordinacion_id
    FROM
        coordinaciones c
            INNER JOIN
        users u ON c.user_id = u.user_id;

-- -----------------------------------------------------
-- View `db-fct`.`vista_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_cursos`;
DROP VIEW IF EXISTS `db-fct`.`vista_cursos` ;
USE `db-fct`;
CREATE  OR REPLACE VIEW `vista_cursos` AS
    SELECT 
        c.curso_id,
        c.alumno_id,
        c.grupo_id,
        g.tutor_id,
        c.horas_hechas,
        c.rating,
        c.observaciones,
        c.posibles_empresas,
        g.numero,
        g.horario,
        g.anexo_ocho,
        g.ciclo_lectivo_id,
        g.ciclo_id,
        ci.name,
        ci.acronimo
    FROM
        cursos c
            INNER JOIN
        grupos g ON g.grupo_id = c.grupo_id
            INNER JOIN
        ciclos_lectivos cl ON cl.ciclo_lectivo_id = g.ciclo_lectivo_id
			AND cl.fecha_fin IS NULL
            INNER JOIN
        ciclos ci ON ci.ciclo_id = g.ciclo_id
            INNER JOIN
        tutores t ON t.tutor_id = g.tutor_id;

-- -----------------------------------------------------
-- View `db-fct`.`vista_tutores_ciclo_lectivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_tutores_ciclo_lectivo`;
DROP VIEW IF EXISTS `db-fct`.`vista_tutores_ciclo_lectivo` ;
USE `db-fct`;
CREATE  OR REPLACE VIEW `vista_tutores_ciclo_lectivo` AS
SELECT
	t.tutor_id,
    t.user_id,
    u.name,
    u.email,
    g.grupo_id,
    g.numero,
    g.ciclo_id,
    g.ciclo_lectivo_id,
    cl.nombre
FROM
tutores t
INNER JOIN users u ON u.user_id = t.user_id
INNER JOIN grupos g ON g.tutor_id = t.tutor_id
AND g.deleted_at IS NULL
INNER JOIN ciclos_lectivos cl ON cl.ciclo_lectivo_id = g.ciclo_lectivo_id
AND cl.deleted_at IS NULL;

-- -----------------------------------------------------
-- View `db-fct`.`vista_all_alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_all_alumnos`;
DROP VIEW IF EXISTS `db-fct`.`vista_all_alumnos` ;
USE `db-fct`;
CREATE OR REPLACE VIEW `vista_all_alumnos` AS
    SELECT 
        u.user_id,
        u.name AS nombre_alumno,
        u.email,
        a.alumno_id,
        a.convocatoria,
        a.dni,
        a.nia,
        a.nuss,
        a.phone,
        a.address
    FROM
        users u
            INNER JOIN
        alumnos a ON u.user_id = a.user_id
    ORDER BY u.name , u.email;

-- -----------------------------------------------------
-- View `db-fct`.`vista_alumnos_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_alumnos_curso`;
DROP VIEW IF EXISTS `db-fct`.`vista_alumnos_curso` ;
USE `db-fct`;
CREATE OR REPLACE VIEW `vista_alumnos_curso` AS
    SELECT 
        u.user_id,
        u.name AS nombre_alumno,
        u.email,
        a.alumno_id,
        a.convocatoria,
        a.dni,
        a.nia,
        a.nuss,
        a.phone,
        a.address,
        c.curso_id,
        c.horas_hechas,
        c.rating,
        c.observaciones,
        c.posibles_empresas,
        g.grupo_id
    FROM
        users u
            INNER JOIN
        alumnos a ON u.user_id = a.user_id
            INNER JOIN
        cursos c ON a.alumno_id = c.alumno_id
            INNER JOIN
        grupos g ON g.grupo_id = c.grupo_id
    ORDER BY u.name , u.email;

-- -----------------------------------------------------
-- View `db-fct`.`vista_empresas_plazas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_empresas_plazas`;
DROP VIEW IF EXISTS `db-fct`.`vista_empresas_plazas` ;
USE `db-fct`;
CREATE  OR REPLACE VIEW `vista_empresas_plazas` AS
    SELECT 
        e.empresa_id,
        e.propuesta_por,
        e.observaciones,
        e.estado,
        e.nombre AS nombre_empresa,
        e.cif,
        e.email,
        e.sector,
        e.address,
        e.phone,
        e.persona_contacto,
        e.fecha_contacto,
        e.hay_convenio,
        e.numero_convenio,
        p.plaza_id,
        p.plazas,
        c.ciclo_id,
        c.name AS nombre_ciclo,
        c.acronimo,
        c.nivel,
        c.familia_profesional,
        c.horas_practicas
    FROM
        empresas e
            LEFT JOIN
        plazas p ON e.empresa_id = p.empresa_id
            LEFT JOIN
        ciclos c ON c.ciclo_id = p.ciclo_id
            AND c.deleted_at IS NULL;

-- -----------------------------------------------------
-- View `db-fct`.`vista_empresas_tutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_empresas_tutores`;
DROP VIEW IF EXISTS `db-fct`.`vista_empresas_tutores` ;
USE `db-fct`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `db-fct`.`vista_empresas_tutores` AS select `e`.`empresa_id` AS `empresa_id`,`e`.`nombre` AS `nombre`,`e`.`estado` AS `estado`,`e`.`cif` AS `cif`,`e`.`email` AS `email`,`e`.`sector` AS `sector`,`e`.`address` AS `address`,`e`.`phone` AS `phone`,`e`.`numero_plazas` AS `numero_plazas`,`e`.`persona_contacto` AS `persona_contacto`,`e`.`propuesta_por` AS `propuesta_por`,`e`.`hay_convenio` AS `hay_convenio`,`e`.`numero_convenio` AS `numero_convenio`,`e`.`fecha_contacto` AS `fecha_contacto`,`e`.`observaciones` AS `observaciones`,`u`.`user_id` AS `id_usuario`,`u`.`name` AS `nombre_usuario`,`u`.`email` AS `email_usuario`,`u`.`role` AS `rol_usuario`,`t`.`tutor_empresa_id` AS `tutor_empresa_id`,`t`.`nombre` AS `nombre_tutor`,`t`.`email` AS `email_tutor`,`t`.`telefono` AS `telefono_tutor`,`t`.`dni` AS `dni_tutor` from ((`db-fct`.`empresas` `e` left join `db-fct`.`users` `u` on((`e`.`propuesta_por` = `u`.`user_id`))) left join `db-fct`.`tutores_empresas` `t` on((`t`.`empresa_id` = `e`.`empresa_id`)));

-- -----------------------------------------------------
-- View `db-fct`.`vista_alumno_ciclos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`vista_alumno_ciclos`;
DROP VIEW IF EXISTS `db-fct`.`vista_alumno_ciclos` ;
USE `db-fct`;
CREATE  OR REPLACE VIEW `vista_alumno_ciclos` AS
    SELECT 
        cl.ciclo_lectivo_id,
        g.grupo_id,
        g.numero,
        ci.ciclo_id,
        CONCAT(g.numero, 'º (', ci.acronimo, ')') AS grupo_nombre,
        a.alumno_id
    FROM
        alumnos a
            INNER JOIN
        cursos c ON a.alumno_id = c.alumno_id
            INNER JOIN
        grupos g ON g.grupo_id = c.grupo_id
            AND g.deleted_at IS NULL
            INNER JOIN
        ciclos_lectivos cl ON g.ciclo_lectivo_id = cl.ciclo_lectivo_id
            AND cl.deleted_at IS NULL
            INNER JOIN
        ciclos ci ON ci.ciclo_id = g.ciclo_id
            AND ci.deleted_at IS NULL;

-- -----------------------------------------------------
-- View `db-fct`.`view_reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`view_reviews`;
DROP VIEW IF EXISTS `db-fct`.`view_reviews` ;
USE `db-fct`;
CREATE  OR REPLACE VIEW `view_reviews` AS
    SELECT 
        r.review_id,
        r.user_id,
        r.empresa_id,
        r.score,
        r.comment,
        r.estado AS review_estado,
        e.propuesta_por,
        e.observaciones,
        e.estado AS empresa_estado,
        e.nombre AS nombre_empresa,
        u.name AS nombre_usuario,
        u.email
    FROM
        reviews r
            INNER JOIN
        empresas e ON r.empresa_id = e.empresa_id
            AND e.deleted_at IS NULL
            INNER JOIN
        users u ON u.user_id = r.user_id
            AND u.deleted_at IS NULL
    WHERE
        r.deleted_at IS NULL;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
