-- MySQL Script generated by MySQL Workbench
-- Wed May 28 15:34:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db-fct
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-fct
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-fct` DEFAULT CHARACTER SET utf8mb3 ;
USE `db-fct` ;

-- -----------------------------------------------------
-- Table `db-fct`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`users` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`users` (
  `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `updated_password` TINYINT NOT NULL DEFAULT '0',
  `is_admin` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`alumnos` (
  `alumno_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `convocatoria` INT NOT NULL DEFAULT '3',
  `nombre` VARCHAR(255) NOT NULL,
  `dni` VARCHAR(9) NULL DEFAULT NULL,
  `nia` VARCHAR(8) NULL DEFAULT NULL,
  `nuss` VARCHAR(11) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `curriculum_file` VARCHAR(255) NULL DEFAULT NULL,
  `anexo_ocho` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`alumno_id`),
  INDEX `fk_alumnos_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`alumnos_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`alumnos_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`alumnos_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`anexos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`anexos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`anexos` (
  `anexo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alumno_id` BIGINT UNSIGNED NOT NULL,
  `anexo_file` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`anexo_id`),
  INDEX `fk_anexos_alumnos_idx` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `fk_anexos_alumnos`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db-fct`.`alumnos` (`alumno_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`ciclos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`ciclos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`ciclos` (
  `ciclo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Ciclo formativo',
  `name` VARCHAR(255) NOT NULL,
  `acronimo` VARCHAR(10) NOT NULL,
  `nivel` ENUM('BASICO', 'MEDIO', 'SUPERIOR') NOT NULL,
  `familia_profesional` VARCHAR(255) NOT NULL,
  `horas_practicas` SMALLINT UNSIGNED NOT NULL COMMENT 'Determina las horas máximas de prácticas de cada ciclo',
  PRIMARY KEY (`ciclo_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`ciclos_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`ciclos_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`ciclos_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`coordinaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`coordinaciones` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`coordinaciones` (
  `coordinacion_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`coordinacion_id`),
  INDEX `fk_coordinaciones_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_coordinaciones_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`coordinaciones_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`coordinaciones_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`coordinaciones_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`grupos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`grupos` (
  `grupo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ciclo_id` BIGINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `acronimo` VARCHAR(10) NOT NULL,
  `horario` ENUM('DIURNO', 'VESPERTINO', 'NOCHE') NOT NULL DEFAULT 'DIURNO',
  `ciclo_lectivo` VARCHAR(9) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`grupo_id`),
  INDEX `fk_grupos_ciclos_idx` (`ciclo_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_ciclos`
    FOREIGN KEY (`ciclo_id`)
    REFERENCES `db-fct`.`ciclos` (`ciclo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`cursos` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`cursos` (
  `curso_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alumno_id` BIGINT UNSIGNED NOT NULL,
  `grupo_id` BIGINT UNSIGNED NOT NULL,
  `year` SMALLINT UNSIGNED NOT NULL,
  `horas_hechas` TINYINT UNSIGNED NOT NULL,
  `apto` TINYINT NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `observaciones` VARCHAR(2047) NULL DEFAULT NULL,
  PRIMARY KEY (`curso_id`),
  INDEX `fk_cursos_alumnos_idx` (`alumno_id` ASC) VISIBLE,
  INDEX `fk_cursos_grupos_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_alumnos`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db-fct`.`alumnos` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_grupos`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `db-fct`.`grupos` (`grupo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`cursos_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`cursos_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`cursos_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`documentaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`documentaciones` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`documentaciones` (
  `documentacion_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alumno_id` BIGINT UNSIGNED NOT NULL,
  `doc_file` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`documentacion_id`),
  INDEX `fk_anexos_alumnos_idx` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `fk_documentaciones_alumnos`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db-fct`.`alumnos` (`alumno_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`empresas` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`empresas` (
  `empresa_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `propuesta_por` BIGINT UNSIGNED NOT NULL,
  `observaciones` VARCHAR(2047) NULL DEFAULT NULL,
  `estado` ENUM('PENDIENTE', 'ACEPTADO', 'DENEGADO') NOT NULL DEFAULT 'PENDIENTE',
  `nombre` VARCHAR(255) NOT NULL,
  `cif` VARCHAR(9) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `sector` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `persona_contacto` VARCHAR(255) NULL DEFAULT NULL,
  `fehca_contacto` DATE NULL DEFAULT NULL,
  `hay_convenio` TINYINT NULL DEFAULT '0',
  `numero_convenio` VARCHAR(9) NULL DEFAULT NULL,
  `fecha_contacto` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`empresa_id`),
  INDEX `fk_empresas_users_idx` (`propuesta_por` ASC) VISIBLE,
  CONSTRAINT `fk_empresas_users`
    FOREIGN KEY (`propuesta_por`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`empresas_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`empresas_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`empresas_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutores` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutores` (
  `tutor_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`tutor_id`),
  INDEX `fk_tutores_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tutores_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutores_empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutores_empresas` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutores_empresas` (
  `tutor_empresa_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`tutor_empresa_id`),
  INDEX `fk_turores_empresas_empresas_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_turores_empresas_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`fcts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`fcts` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`fcts` (
  `fct_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alumno_id` BIGINT UNSIGNED NOT NULL,
  `tutor_id` BIGINT UNSIGNED NOT NULL,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `grupo_id` BIGINT UNSIGNED NOT NULL,
  `tutor_empresa_id` BIGINT UNSIGNED NOT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `observaciones` VARCHAR(2047) NULL DEFAULT NULL,
  `apto` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`fct_id`),
  INDEX `fk_fcts_alumnos_idx` (`alumno_id` ASC) VISIBLE,
  INDEX `fk_fcts_tutores_idx` (`tutor_id` ASC) VISIBLE,
  INDEX `fk_fcts_empresas_idx` (`empresa_id` ASC) VISIBLE,
  INDEX `fk_fcts_turores_empresas_idx` (`tutor_empresa_id` ASC) VISIBLE,
  INDEX `fk_fcts_grupos_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_fcts_alumnos`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db-fct`.`alumnos` (`alumno_id`),
  CONSTRAINT `fk_fcts_grupos`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `db-fct`.`grupos` (`grupo_id`),
  CONSTRAINT `fk_fcts_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`),
  CONSTRAINT `fk_fcts_tutores`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `db-fct`.`tutores` (`tutor_id`),
  CONSTRAINT `fk_fcts_tutores_empresas`
    FOREIGN KEY (`tutor_empresa_id`)
    REFERENCES `db-fct`.`tutores_empresas` (`tutor_empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`plazas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`plazas` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`plazas` (
  `plaza_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `ciclo_id` BIGINT UNSIGNED NOT NULL,
  `plazas` INT NOT NULL,
  PRIMARY KEY (`plaza_id`),
  INDEX `fk_plazas_empresas_idx` (`empresa_id` ASC) VISIBLE,
  INDEX `fk_plazas_ciclos_idx` (`ciclo_id` ASC) VISIBLE,
  CONSTRAINT `fk_plazas_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`),
  CONSTRAINT `fk_plazas_ciclos`
    FOREIGN KEY (`ciclo_id`)
    REFERENCES `db-fct`.`ciclos` (`ciclo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`plazas_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`plazas_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`plazas_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`reviews` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`reviews` (
  `review_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `score` TINYINT NOT NULL COMMENT 'El valor debe estar comprometido entre 0 y 5.',
  `comment` VARCHAR(2047) NULL DEFAULT NULL,
  `estado` ENUM('VISIBLE', 'ELIMINADO') NULL DEFAULT 'VISIBLE',
  `made_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`),
  INDEX `fk_resenias_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reviews_empresas_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db-fct`.`users` (`user_id`),
  CONSTRAINT `fk_reviews_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `db-fct`.`empresas` (`empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`reviews_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`reviews_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`reviews_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutores_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutores_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutores_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutorias` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutorias` (
  `tutoria_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tutor_id` BIGINT UNSIGNED NOT NULL,
  `grupo_id` BIGINT UNSIGNED NOT NULL,
  `year` SMALLINT NOT NULL,
  PRIMARY KEY (`tutoria_id`),
  INDEX `fk_tutorias_tutores_idx` (`tutor_id` ASC) INVISIBLE,
  INDEX `fk_tutorias_grupos_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tutorias_tutores`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `db-fct`.`tutores` (`tutor_id`),
  CONSTRAINT `fk_tutorias_grupos`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `db-fct`.`grupos` (`grupo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`tutorias_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`tutorias_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`tutorias_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db-fct`.`users_seq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db-fct`.`users_seq` ;

CREATE TABLE IF NOT EXISTS `db-fct`.`users_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
